apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ofk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-oppfolgingstjenesten-gateway_ofk_no
  fintlabs.no/org-id: ofk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "ofk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "ofk.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/beta"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/ofk-no/api/oppfolgingstjenesten"
    target:
      kind: Application
      name: fint-flyt-oppfolgingstjenesten-gateway

