name: CI

on:
  push:
    branches-ignore:
      - main

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - uses: gradle/wrapper-validation-action@v2.1.2
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.12.0
        with:
          arguments: check
